// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
});

// Prisma configuration is managed through the .prismarc.json file or prisma/schema.prisma
// This file is not needed for standard Prisma setups
